name: "Deploy to Vercel Production"

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'  # matches x.y.z only

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "24"

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Get version info
        id: version
        run: |
          echo "describe=$(git describe --always --tags --dirty=+)" >> $GITHUB_OUTPUT
          echo "short_sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Load .env into environment
        run: grep -v '^#' .env | grep '=' >> $GITHUB_ENV

      - name: Pull Vercel environment
        run: npx vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

      - name: Build
        run: npx vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          NUXT_PUBLIC_COMMIT_SHA: ${{ steps.version.outputs.describe }}
          NUXT_PUBLIC_COMMIT_SHORT_SHA: ${{ steps.version.outputs.short_sha }}
          NUXT_PUBLIC_COMMIT_REF: ${{ github.ref_name }}
          NUXT_PUBLIC_BUILD_DATE: ${{ github.event.repository.updated_at }}
          NUXT_PUBLIC_RUN_ID: ${{ github.run_id }}

      - name: Deploy to Vercel Production
        run: |
          npx vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }} \
            --meta githubCommitRef=${{ github.ref_name }} \
            --meta githubCommitSha=${{ github.sha }} \
            --meta githubOrg=${{ github.repository_owner }} \
            --meta githubRepo=${{ github.event.repository.name }} \
            --meta githubCommitAuthorLogin=${{ github.actor }}
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
